apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: portfolio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - www.douglasbrunner.name
    secretName: portfolio-tls
  rules: 
  - host: www.douglasbrunner.name
    http:
      paths:
      - backend:
          serviceName: portfolio-svc
          servicePort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-svc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio 
    spec:
      containers:
      - name: portfolio
        image: registry.gitlab.com/douglasbrunner/portfolio:1.1.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: gitlabreg

